### ISSUE TITLE
政策更新导致上游接口失效

### ISSUE THREAD

**Issue by ddawx123** [panghaibin/RiskLevelAPI#3]
中高风险地区API调整了，好像现在这个接口已经失效了

**Comment by panghaibin** [comment]
~~卫健委官网 http://bmfw.www.gov.cn/yqfxdjcx/risk.html 依然是提供高中低三类数据，可能是部分地区报送的数据没有及时更新。~~ 另外，从commit记录来看程序还能获取到接口数据

目前接口的数据已变更为高低两类，也能正常获取。具体有待进一步观察。
